[servers]
#[servers.localhost]
#host	= "localhost"
#port	= "local"

#[servers.remote01]
#host	= "xxxx.xxxx.xxxx.xxxx"
#port	= "22"
#user	= "keides2"
#keyPath	= "/home/keides2/.ssh/id_rsa"

[slack]
hookURL = "https://outlook.office.com/webhook/5128e755-snip-e85b83bb4046/IncomingWebhook/xxxx/972a30b3-snip-71f796dd7131"
channel = "#VulsReport"
authUser = "VulsReporter"

[servers.Project-A]
type = "pseudo"
cpeNames = [
	"cpe:/o:microsoft:windows_server_2012:r2::~~standard~~x64~",
#	"cpe:/a:microsoft:internet_explorer:11",
	"cpe:/a:microsoft:internet_explorer:11:-",
	"cpe:/a:oracle:jre:1.8.0:update_40",
	"cpe:/a:oracle:jre:1.8.0:update_152",
	"cpe:/a:oracle:jre:1.8.0:update_181",
#	"cpe:/a:oracle:jdk:1.8.0:update_40",
#	"cpe:/a:oracle:jdk:1.8.0:update_152",
#	"cpe:/a:oracle:jdk:1.8.0:update_181",
	"cpe:/a:oracle:weblogic_server:12.2.1.3.0",
	"cpe:/a:apache:http_server:2.4.27",
	"cpe:/o:oracle:linux:6:9",
	"cpe:/a:oracle:database:12.1.0.2",
	"cpe:/o:redhat:enterprise_linux:7.3",
	"cpe:/o:microsoft:windows_10:1809::~~~~x64~",
	"cpe:/h:cisco:catalyst_2901:-",
	"cpe:/h:cisco:catalyst_2960:-",
	"cpe:/a:cisco:catalyst_29xx_supervisor_software:-",
	"cpe:/h:fortinet:fortigate-100e:-",
	"cpe:/a:imperva:securesphere:11.0",
	"cpe:/a:citrix:netscaler:12.0",
	"cpe:/a:citrix:netscaler_application_delivery_controller:12.0",
#	"cpe:/a:citrix:netscaler_gateway:12.0",
#	"cpe:/o:citrix:netscaler_gateway_firmware:12.0",
	]


[email]
smtpAddr = "localhost"
smtpPort = "25"
from = "vuls@abcd.com"
to = [
	"xxxx@abcd.com",
	"yyyy@abcd.com",
	]
cc = [
	"zzzz@abcd.com",
	"wwww@abcd.com",
	]
subjectPrefix = "[VulsReport]"


