[servers]
[servers.Project-A]
type = "pseudo"
cpeNames = [
	"cpe:2.3:a:acl_project:acl:2.2.51:*:*:*:*:*:*:*",
	"cpe:2.3:a:alsa-project:alsa:1.1.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:commons_collections:3.2.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:apr-util:1.5.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:at-spi2-atk:2.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:linux_audit_project:linux_audit:2.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:avahi:avahi:0.6.31:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:bash:4.2.46:*:*:*:*:*:*:*",
	"cpe:2.3:a:isc:bind:9.11.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:binutils:2.27:*:*:*:*:*:*:*",
	"cpe:2.3:a:bzip:bzip2:1.0.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:cairographics:cairo:1.15.12:*:*:*:*:*:*:*",
	"cpe:2.3:a:chrony_project:chrony:3.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:canonical:cloud-init:18.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:coreutils:8.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:cpio:2.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:cracklib_project:cracklib:2.9.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:apple:cups:1.6.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:haxx:curl:7.29.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:cmu:cyrus-sasl:2.1.26:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:dbus:1.10.24:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:dbus-glib:0.100:*:*:*:*:*:*:*",
	"cpe:2.3:a:isc:dhcp:4.2.5:rc1:*:*:*:*:*:*",
	"cpe:2.3:a:dracut_project:dracut:033-502:*:*:*:*:*:*:*",
	"cpe:2.3:a:e2fsprogs_project:e2fsprogs:1.42.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:elfutils_project:elfutils:0.176:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:emacs:24.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:kernel:ethtool:4.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:libexpat:expat:2.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:file_project:file:5.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:findutils:4.5.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:fontconfig_project:fontconfig:2.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:freetype:freetype:2.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:fribidi:1.0.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gcc:4.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:gdk-pixbuf:2.36.12:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:geronimo:1.1.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gettext:0.19.8.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:giflib_project:giflib:4.1.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:glib:2.56.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:glibc:2.17:*:*:*:*:*:*:*",
	"cpe:2.3:a:gmplib:gmp:6.0.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:gnupg:2.0.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gpgme:1.3.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:sil:graphite2:1.3.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:grep:2.20:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:groff:1.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:grub2:2.02:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gzip:1.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:hardlink_project:hardlink:1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:harfbuzz_project:harfbuzz:1.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:http_server:2.4.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:texinfo:5.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:iproute2_project:iproute2:4.11.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:iptables:1.4.21:*:*:*:*:*:*:*",
	"cpe:2.3:a:iputils_project:iputils:s20160308:*:*:*:*:*:*:*",
	"cpe:2.3:a:jansson_project:jansson:2.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:jasper_project:jasper:1.900.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:oracle:openjdk:1.8.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:sun:javamail:1.4.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:cambridge_enterprise:jbig-kit:2.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:json-c_project:json-c:0.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:altlinux:kbd:1.15.5:*:*:*:*:*:*:*",
	"cpe:2.3:o:linux:linux_kernel:3.10:*:*:*:*:*:*:*",
	"cpe:2.3:o:linux:linux_kernel:3.10.0:*:*:*:*:*:arm64:*",
	"cpe:2.3:a:kernel:kmod:20:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:less:458:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcap_project:libcap:2.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcap-ng_project:libcap-ng:0.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcgroup_project:libcgroup:0.41:*:*:*:*:*:*:*",
	"cpe:2.3:a:haxx:libcurl:7.29.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:libdaemon_project:libdaemon:0.14:*:*:*:*:*:*:*",
	"cpe:2.3:a:adiscon:libestr:0.1.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:libevent_project:libevent:2.0.21:*:*:*:*:*:*:*",
	"cpe:2.3:a:rsyslog:libfastjson:0.99.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:libffi_project:libffi:3.0.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:libgcrypt:1.5.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libgomp:4.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:libgpg-error:1.12:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:libice:1.0.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libidn:1.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:libjpeg-turbo:libjpeg-turbo:1.2.90:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libmnl:1.0.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libndp:libndp:1.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libnetfilter_conntrack:1.0.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libnfnetlink:1.0.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:libnl_project:libnl:1.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:libnl_project:libnl:3.2.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:tcpdump:libpcap:1.5.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libpng:libpng:1.5.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:libseccomp_project:libseccomp:2.3.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libselinux:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libsemanage:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libsepol:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:libssh2:libssh2:1.8.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libtasn1:4.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:libtiff:libtiff:4.0.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libtirpc_project:libtirpc:0.2.4:-:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libunistring:0.9.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libuser_project:libuser:0.60:*:*:*:*:*:*:*",
	"cpe:2.3:a:x.org:libx11:1.6.7:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxcb:1.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxcursor:1.1.15:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxext:1.3.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxfixes:5.0.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxi:1.7.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxinerama:1.1.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:xmlsoft:libxml2:2.9.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxrandr:1.5.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:x.org:libxrender:0.9.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:xmlsoft:libxslt:1.1.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxtst:1.2.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:x:libxxf86vm:1.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:pyyaml:libyaml:0.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:log4j:1.2.17:*:*:*:*:*:*:*",
	"cpe:2.3:a:logrotate_project:logrotate:3.8.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:lua:lua:5.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:lz4_project:lz4:1.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:lzo_project:lzo:2.06:*:*:*:*:*:*:*",
	"cpe:2.3:a:heirloom:mailx:12.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:make:3.82:*:*:*:*:*:*:*",
	"cpe:2.3:a:man-db_project:man-db:2.6.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:mesa3d:mesa:18.3.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:modssl:mod_ssl:2.4.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:oracle:mysql:8.0.19:*:*:*:*:*:*:*",
	"cpe:2.3:a:oracle:mysql_connector%2fnet:8.0.19:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:ncurses:5.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:net-tools_project:net-tools:2.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:networkmanager:1.18.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:linux-nfs:nfs-utils:1.3.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:mozilla:netscape_portable_runtime:4.21.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:mozilla:nss:3.44:*:*:*:*:*:*:*",
	"cpe:2.3:a:openldap:openldap:2.4.44:*:*:*:*:*:*:*",
	"cpe:2.3:a:openbsd:openssh:7.4p1:*:*:*:*:*:*:*",
	"cpe:2.3:a:openssl:openssl:*:*:*:*:*:*:*:*",
	"cpe:2.3:a:linux-pam:linux-pam:1.1.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:pango:pango:1.42.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:parted_project:parted:3.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:pcre:pcre:8.32:*:*:*:*:*:*:*",
	"cpe:2.3:a:perl:perl:5.16.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:pixman:pixman:0.34.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:policycoreutils:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:polkit_project:polkit:0.112:*:*:*:*:*:*:*",
	"cpe:2.3:a:popt_project:popt:1.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:postfix:postfix:2.10.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:procps-ng_project:procps-ng:3.3.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:jean-paul_calderone:pyopenssl:0.13.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:python:2.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:decorator:3.4.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:python-requests:requests:2.6.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:setuptools:0.9.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:urllib3:1.10.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:pyyaml_project:pyyaml:3.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:qemu:qemu:2.12.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:readline:6.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:rhnsd:5.0.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:rpcbind_project:rpcbind:0.2.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:rpm:rpm:4.11.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:samba:rsync:3.1.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:rsyslog:rsyslog:8.24.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:sed:4.2.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:debian:shadow-utils:4.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:google:snappy:1.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:sqlite:sqlite:3.7.17:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:subscription-manager:1.24.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:sudo_project:sudo:1.8.23:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:systemd:219:*:*:*:*:*:*:*",
	"cpe:2.3:a:sysvinit_project:sysvinit:2.88:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:tar:1.26:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:tuned:2.11.0:-:*:*:*:*:*:*",
	"cpe:2.3:a:info-zip:unzip:6.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:ustr_project:ustr:1.0.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:kernel:util-linux:2.23.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:vim:vim:7.4.629:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:wget:1.14:*:*:*:*:*:*:*",
	"cpe:2.3:a:w1.fi:wpa_supplicant:2.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:xalan-java:2.7.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:xdg-utils:1.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:xerces-j:2.11.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:tukaani:xz:5.2.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:baseurl:yum:3.4.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:zlib:zlib:1.2.7:*:*:*:*:*:*:*",
	"cpe:2.3:a:pivotal_software:spring_boot:2.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:pivotal_software:spring_security:3.0.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:oracle:mysql_connector%2fnet:8.0.15:*:*:*:*:*:*:*",
	"cpe:2.3:a:pivotal_software:spring_framework:2.1.5:-:*:*:*:*:*:*",
	"cpe:2.3:a:apache:commons_beanutils:1.9.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:pivotal_software:spring_security:4.1.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:apache:maven:3.6.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:getbootstrap:bootstrap:3.0.0:-:*:*:*:*:*:*",
	"cpe:2.3:a:jquery:jquery:1.11.0:-:*:*:*:*:*:*",
	"cpe:2.3:a:jquery:jquery:1.19.0:-:*:*:*:*:*:*",
	"cpe:2.3:a:mit:kerberos_5:1.15.1:-:*:*:*:*:*:*",
	]

[servers.Project-B]
type = "pseudo"
cpeNames = [
	"cpe:2.3:a:acl_project:acl:2.2.51:*:*:*:*:*:*:*",
	"cpe:2.3:a:linux_audit_project:linux_audit:2.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:bash:4.2.46:*:*:*:*:*:*:*",
	"cpe:2.3:a:isc:bind:9.11.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:binutils:2.27:*:*:*:*:*:*:*",
	"cpe:2.3:a:bzip:bzip2:1.0.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:chrony_project:chrony:3.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:canonical:cloud-init:18.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:coreutils:8.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:cpio:2.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:cracklib_project:cracklib:2.9.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:haxx:curl:7.29.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:cmu:cyrus-sasl:2.1.26:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:dbus:1.10.24:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:dbus-glib:0.100:*:*:*:*:*:*:*",
	"cpe:2.3:a:isc:dhcp:4.2.5:rc1:*:*:*:*:*:*",
	"cpe:2.3:a:dracut_project:dracut:033-502:*:*:*:*:*:*:*",
	"cpe:2.3:a:e2fsprogs_project:e2fsprogs:1.42.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:elfutils_project:elfutils:0.176:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:emacs:24.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:kernel:ethtool:4.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:libexpat:expat:2.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:file_project:file:5.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:findutils:4.5.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:freetype:freetype:2.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gcc:4.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gettext:0.19.8.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:glib:2.56.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:glibc:2.17:*:*:*:*:*:*:*",
	"cpe:2.3:a:gmplib:gmp:6.0.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:gnupg:2.0.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gpgme:1.3.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:grep:2.20:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:groff:1.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:grub2:2.02:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:gzip:1.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:hardlink_project:hardlink:1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:texinfo:5.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:iproute2_project:iproute2:4.11.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:iptables:1.4.21:*:*:*:*:*:*:*",
	"cpe:2.3:a:iputils_project:iputils:s20160308:*:*:*:*:*:*:*",
	"cpe:2.3:a:jansson_project:jansson:2.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:json-c_project:json-c:0.11:*:*:*:*:*:*:*",
	"cpe:2.3:a:altlinux:kbd:1.15.5:*:*:*:*:*:*:*",
	"cpe:2.3:o:linux:linux_kernel:3.10:*:*:*:*:*:*:*",
	"cpe:2.3:o:linux:linux_kernel:3.10.0:*:*:*:*:*:arm64:*",
	"cpe:2.3:a:gnu:less:458:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcap_project:libcap:2.22:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcap-ng_project:libcap-ng:0.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:libcgroup_project:libcgroup:0.41:*:*:*:*:*:*:*",
	"cpe:2.3:a:haxx:libcurl:7.29.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:libdaemon_project:libdaemon:0.14:*:*:*:*:*:*:*",
	"cpe:2.3:a:adiscon:libestr:0.1.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:rsyslog:libfastjson:0.99.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:libffi_project:libffi:3.0.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:libgcrypt:1.5.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libgomp:4.8.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnupg:libgpg-error:1.12:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libidn:1.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libmnl:1.0.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libndp:libndp:1.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libnetfilter_conntrack:1.0.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:netfilter:libnfnetlink:1.0.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:libnl_project:libnl:1.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:libnl_project:libnl:3.2.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:tcpdump:libpcap:1.5.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libpng:libpng:1.5.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:libseccomp_project:libseccomp:2.3.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libselinux:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libsemanage:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:libsepol:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:libssh2:libssh2:1.8.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libtasn1:4.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:libunistring:0.9.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:libuser_project:libuser:0.60:*:*:*:*:*:*:*",
	"cpe:2.3:a:xmlsoft:libxml2:2.9.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:xmlsoft:libxslt:1.1.28:*:*:*:*:*:*:*",
	"cpe:2.3:a:pyyaml:libyaml:0.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:logrotate_project:logrotate:3.8.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:lua:lua:5.1.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:lz4_project:lz4:1.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:lzo_project:lzo:2.06:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:make:3.82:*:*:*:*:*:*:*",
	"cpe:2.3:a:man-db_project:man-db:2.6.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:mariadb:mariadb:5.5.64:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:ncurses:5.9:*:*:*:*:*:*:*",
	"cpe:2.3:a:net-tools_project:net-tools:2.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnome:networkmanager:1.18.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:mozilla:netscape_portable_runtime:4.21.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:mozilla:nss:3.44:*:*:*:*:*:*:*",
	"cpe:2.3:a:openldap:openldap:2.4.44:*:*:*:*:*:*:*",
	"cpe:2.3:a:openbsd:openssh:7.4p1:*:*:*:*:*:*:*",
	"cpe:2.3:a:openssl:openssl:*:*:*:*:*:*:*:*",
	"cpe:2.3:a:linux-pam:linux-pam:1.1.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:parted_project:parted:3.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:pcre:pcre:8.32:*:*:*:*:*:*:*",
	"cpe:2.3:a:perl:perl:5.16.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:selinuxproject:policycoreutils:2.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:polkit_project:polkit:0.112:*:*:*:*:*:*:*",
	"cpe:2.3:a:popt_project:popt:1.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:postfix:postfix:2.10.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:procps-ng_project:procps-ng:3.3.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:jean-paul_calderone:pyopenssl:0.13.1:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:python:2.7.5:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:decorator:3.4.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:python-requests:requests:2.6.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:setuptools:0.9.8:*:*:*:*:*:*:*",
	"cpe:2.3:a:python:urllib3:1.10.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:pyyaml_project:pyyaml:3.10:*:*:*:*:*:*:*",
	"cpe:2.3:a:qemu:qemu:2.12.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:readline:6.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:rhnsd:5.0.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:rpm:rpm:4.11.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:samba:rsync:3.1.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:rsyslog:rsyslog:8.24.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:sed:4.2.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:debian:shadow-utils:4.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:google:snappy:1.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:sqlite:sqlite:3.7.17:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:subscription-manager:1.24.13:*:*:*:*:*:*:*",
	"cpe:2.3:a:sudo_project:sudo:1.8.23:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:systemd:219:*:*:*:*:*:*:*",
	"cpe:2.3:a:sysvinit_project:sysvinit:2.88:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:tar:1.26:*:*:*:*:*:*:*",
	"cpe:2.3:a:redhat:tuned:2.11.0:-:*:*:*:*:*:*",
	"cpe:2.3:a:info-zip:unzip:6.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:ustr_project:ustr:1.0.4:*:*:*:*:*:*:*",
	"cpe:2.3:a:kernel:util-linux:2.23.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:vim:vim:7.4.629:*:*:*:*:*:*:*",
	"cpe:2.3:a:gnu:wget:1.14:*:*:*:*:*:*:*",
	"cpe:2.3:a:w1.fi:wpa_supplicant:2.6:*:*:*:*:*:*:*",
	"cpe:2.3:a:freedesktop:xdg-utils:1.1.0:*:*:*:*:*:*:*",
	"cpe:2.3:a:tukaani:xz:5.2.2:*:*:*:*:*:*:*",
	"cpe:2.3:a:baseurl:yum:3.4.3:*:*:*:*:*:*:*",
	"cpe:2.3:a:zlib:zlib:1.2.7:*:*:*:*:*:*:*",
	"cpe:2.3:a:mit:kerberos_5:1.15.1:-:*:*:*:*:*:*",
	]


[email]
smtpAddr = "localhost"
smtpPort = "25"
from = "vuls@abcd.com"
to = [
	"aaaa@abcd.com",
	"bbbb@abcd.com",
	]
cc = [
	"cccc@abcd.com",
	"dddd@abcd.com",
	]
subjectPrefix = "[VulsReport]"
